/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/ui-kit/button/Button.vue')['default']
    FileUploader: typeof import('./src/components/ui-kit/file-uploader/FileUploader.vue')['default']
    MsButton: typeof import('./src/components/ui-kit/button/msButton.vue')['default']
    MsIcon: typeof import('./src/components/ui-kit/icons/MsIcon.vue')['default']
    MSIcon: typeof import('./src/components/ui-kit/icons/MSIcon.vue')['default']
    MsLabel: typeof import('./src/components/ui-kit/label/msLabel.vue')['default']
    MsSpinner: typeof import('./src/components/ui-kit/spinner/MsSpinner.vue')['default']
    MsSpinnerIcon: typeof import('./src/components/ui-kit/icons/MsSpinnerIcon.vuee')['default']
    MsTypogrphy: typeof import('./src/components/ui-kit/typography/msTypogrphy.vue')['default']
    RequiredIcon: typeof import('./src/components/ui-kit/icons/RequiredIcon.vue')['default']
    SpinnerIcon: typeof import('./src/components/ui-kit/icons/SpinnerIcon.vue')['default']
  }
}
